---
run:
  deadline: 5m
  tests: false
  skip-files:
    - ".*\\.pb\\.go$"

linters-settings:
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 30
  maligned:
    suggest-new: true
  dupl:
    threshold: 100

linters:
  enable-all: true
  disable:
    - errcheck
    - lll
